using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ClassicUO.Game.Data;
using ClassicUO.Utility;
using ClassicUO.Utility.Logging;

namespace ClassicUO.Localization
{
    static class LocalizationManager
    {
        private static readonly string[] _dict = new string[(int) LocalizationProperties.COUNT_INTERNAL_USE_ONLY];



        static LocalizationManager()
        {
            string path = FileSystemHelper.CreateFolderIfNotExists(Path.Combine(CUOEnviroment.ExecutablePath, "Data"), "Languages");
            //TODO:
            
            CreateDefault();
        }


        public static string Get(LocalizationProperties prop)
        {
            string s = _dict[(int) prop];

            if (!string.IsNullOrEmpty(s))
            {
                return s;
            }

            return "<CUO_ERROR_not_found>";
        }


        public static void LoadFile(string file)
        {
            FileInfo fileInfo = new FileInfo(Path.Combine(CUOEnviroment.ExecutablePath, "Data", "Languages", file));

            if (!fileInfo.Exists)
            {
                Log.Warn($"localization file not found: '{fileInfo.FullName}'");
            }
            else
            {
                // File format:
                // INDEX=VALUE
                using (StreamReader reader = new StreamReader(File.OpenRead(fileInfo.FullName)))
                {
                    while (!reader.EndOfStream)
                    {
                        ReadOnlySpan<char> line = reader.ReadLine().AsSpan();

                        int index = line.IndexOf('=');

                        if (index > 0)
                        {
                            ReadOnlySpan<char> key = line.Slice(0, index - 1);
                            ReadOnlySpan<char> value = line.Slice(index);

                            if (int.TryParse(key.ToString(), out index) && !value.IsEmpty && index >= 0 && index < (int) LocalizationProperties.COUNT_INTERNAL_USE_ONLY)
                            {
                                _dict[index] = value.ToString();

                                Log.Debug($"replaced: [{index}] - [{_dict[index]}]");
                            }
                        }
                    }
                }
            }
        }
        

        private static void CreateDefault()
        {
            Log.Trace("creating default english localization...");

            _dict[(int) LocalizationProperties.AlwaysRunIsNowOff] = "Always run is now off.";
            _dict[(int) LocalizationProperties.ThereIsAlreadyAConference] = "There is already a conference of that name.";
            _dict[(int) LocalizationProperties.YouAreDead] = "You are dead.";
            _dict[(int) LocalizationProperties.BatWing] = "Bat Wing";
            _dict[(int) LocalizationProperties.ConnectionLost0] = "Connection lost:\n{0}";
            _dict[(int) LocalizationProperties.ThatIsNotTheCorrectPassword] = "That is not the correct password.";
            _dict[(int) LocalizationProperties.BlackPearl] = "Black Pearl";
            _dict[(int) LocalizationProperties.DaemonBlood] = "Daemon Blood";
            _dict[(int) LocalizationProperties.YouCanNowReceivePM] = "You can now receive private messages.";
            _dict[(int) LocalizationProperties.EmoteChar] = "*";
            _dict[(int) LocalizationProperties.ThatIsNotAValidConferenceName] = "That is not a valid conference name.";
            _dict[(int) LocalizationProperties.Alliance0] = "[Alliance][{0}]";
            _dict[(int) LocalizationProperties.YouMustHaveOperatorStatus] = "You must have operator status to do this.";
            _dict[(int) LocalizationProperties.Garlic] = "Garlic";
            _dict[(int) LocalizationProperties.TargetAnItemToGrabIt] = "Target an Item to grab it.";
            _dict[(int) LocalizationProperties.CannotDeleteThisGroup] = "Cannot delete this group.";
            _dict[(int) LocalizationProperties.Backpack] = "Backpack";
            _dict[(int) LocalizationProperties.Guild0] = "[Guild][{0}]";
            _dict[(int) LocalizationProperties.Dexterity] = "dexterity";
            _dict[(int) LocalizationProperties.Combat] = "Combat";
            _dict[(int) LocalizationProperties.Intelligence] = "intelligence";
            _dict[(int) LocalizationProperties.GrabBagNotFound] = "Grab Bag not found, setting to Backpack.";
            _dict[(int) LocalizationProperties.NoName] = "No name";
            _dict[(int) LocalizationProperties.Thieving] = "Thieving";
            _dict[(int) LocalizationProperties.Name0Val1] = "Name: {0} - {1:F1}";
            _dict[(int) LocalizationProperties.Wilderness] = "Wilderness";
            _dict[(int) LocalizationProperties.ThereIsNoConferenceNamed1] = "There is no conference named '%1'.";
            _dict[(int) LocalizationProperties.YouAreBanning1FromThisConference] = "You are banning %1 from this conference.";
            _dict[(int) LocalizationProperties.Target0] = "Target: {0}";
            _dict[(int) LocalizationProperties.NowFollowing] = "Now following.";
            _dict[(int) LocalizationProperties.YouAreNotShowingYourCharName] = "You are no longer showing your character name to any players who inquire with the whois command.";
            _dict[(int) LocalizationProperties.Ginseng] = "Ginseng";
            _dict[(int) LocalizationProperties.Weight] = "Weight";
            _dict[(int) LocalizationProperties.AFierceStormApproaches] = "A fierce storm approaches.";
            _dict[(int) LocalizationProperties.YouAreNowIgnoring1] = "You are now ignoring %1.";
            _dict[(int) LocalizationProperties.PasswordToTheConferenceChanged] = "The password to the conference has been changed.";
            _dict[(int) LocalizationProperties.Connecting] = "Connecting...";
            _dict[(int) LocalizationProperties.Your0HasChangedBy1ItIsNow2] = "Your {0} has changed by {1}.  It is now {2}";
            _dict[(int) LocalizationProperties.System] = "System";
            _dict[(int) LocalizationProperties.Salute] = "Salute";
            _dict[(int) LocalizationProperties.Party0] = "[Party][{0}]";
            _dict[(int) LocalizationProperties.YouSee] = "You see";
            _dict[(int) LocalizationProperties.EntityNotFound] = "Entity not found.";
            _dict[(int) LocalizationProperties.EnteringBritannia] = "Entering Britannia...";
            _dict[(int) LocalizationProperties.Strength] = "strength";
            _dict[(int) LocalizationProperties.NoLongerHasSpeakingPrivileges] = "%1 no longer has speaking privileges in this conference.";
            _dict[(int) LocalizationProperties.IsNoLongerAConferenceModerator] = "%1 is no longer a conference moderator.";
            _dict[(int) LocalizationProperties.Journal] = "Journal";
            _dict[(int) LocalizationProperties.ThereIsNoPlayerNamed1] = "There is no player named '%1'.";
            _dict[(int) LocalizationProperties.ItBeginsToRain] = "It begins to rain.";
            _dict[(int) LocalizationProperties.ItBeginsToSnow] = "It begins to snow.";
            _dict[(int) LocalizationProperties.VerifyingAccount] = "Verifying Account...";
            _dict[(int) LocalizationProperties.ClassicUOLink] = "https://classicuo.eu";
            _dict[(int) LocalizationProperties.NoxCrystal] = "Nox Crystal";
            _dict[(int) LocalizationProperties.SulfurousAsh] = "Sulfurous Ash";
            _dict[(int) LocalizationProperties.Pathfinding] = "Pathfinding!";
            _dict[(int) LocalizationProperties.EveryoneWillHaveSpeakingPrivs] = "From now on, everyone in the conference will have speaking privileges by default.";
            _dict[(int) LocalizationProperties.YouAreNoLongerIgnoring1] = "You are no longer ignoring %1.";
            _dict[(int) LocalizationProperties.Decreased] = "decreased";
            _dict[(int) LocalizationProperties.Conference1RenamedTo2] = "Conference %1 renamed to %2.";
            _dict[(int) LocalizationProperties.AConferenceModeratorKickedYou] = "%1, a conference moderator, has kicked you out of the conference.";
            _dict[(int) LocalizationProperties.QuitPrompt] = "Quit\nUltima Online?";
            _dict[(int) LocalizationProperties.HasChosenToNotReceivePM] = "%1 has chosen to not receive private messages at the moment.";
            _dict[(int) LocalizationProperties.BannedYouFromTheConference] = "%1, a conference moderator, has banned you from the conference.";
            _dict[(int) LocalizationProperties.NowHasSpeakingPrivileges] = "%1 now has speaking privileges in this conference.";
            _dict[(int) LocalizationProperties.PigIron] = "Pig Iron";
            _dict[(int) LocalizationProperties.HasRemovedYouFromModerators] = "%1 has removed you from the list of conference moderators.";
            _dict[(int) LocalizationProperties.English] = "English";
            _dict[(int) LocalizationProperties.TargetSystemNotImplemented] = "[WARN] - TargetSystem On/Off not implemented";
            _dict[(int) LocalizationProperties.CreatingCharacter] = "Creating character...";
            _dict[(int) LocalizationProperties.HasChosenToIgnoreYou] = "%1 has chosen to ignore you. None of your messages to them will get through.";
            _dict[(int) LocalizationProperties.YouHaveJoinedThe0Channel] = "You have joined the '{0}' channel.";
            _dict[(int) LocalizationProperties.YouHaveBeenBanned] = "You have been banned from this conference.";
            _dict[(int) LocalizationProperties.ItemID0Hue1] = "Item ID: {0}\nHue: {1}";
            _dict[(int) LocalizationProperties.CheckYourConnectionAndTryAgain] = "Check your internet connection and try again";
            _dict[(int) LocalizationProperties.Bow] = "Bow";
            _dict[(int) LocalizationProperties.IsRemainingAnonymous] = "%1 is remaining anonymous.";
            _dict[(int) LocalizationProperties.Magic] = "Magic";
            _dict[(int) LocalizationProperties.Czech] = "Czech";
            _dict[(int) LocalizationProperties.Radar] = "Radar";
            _dict[(int) LocalizationProperties.TradeSkills] = "Trade Skills";
            _dict[(int) LocalizationProperties.Bloodmoss] = "Bloodmoss";
            _dict[(int) LocalizationProperties.YourUOClientVersionIsInvalid] = "Your Ultima Online client version seems to be invalid.\nDownload the official Launcher to setup and run your game.\n\nLink: classicuo.eu";
            _dict[(int) LocalizationProperties.IsNowAConferenceModerator] = "%1 is now a conference moderator.";
            _dict[(int) LocalizationProperties.CurrentDateTimeNowIs0] = "Current DateTime.Now is {0}";
            _dict[(int) LocalizationProperties.SpidersSilk] = "Spiders Silk";
            _dict[(int) LocalizationProperties.Nightshade] = "Nightshade";
            _dict[(int) LocalizationProperties.TheConferenceNamed1IsFull] = "Sorry--the conference named '%1' is full and no more players are allowed in.";
            _dict[(int) LocalizationProperties.YourUODirectoryIsInvalid] = "Your Ultima Online directory seems to be invalid.\nDownload the official Launcher to setup and run your game.\n\nLink: classicuo.eu";
            _dict[(int) LocalizationProperties.YouAreAlreadyIgnoringMaximum] = "You are already ignoring the maximum number of people.";
            _dict[(int) LocalizationProperties.StoppedFollowing] = "Stopped following.";
            _dict[(int) LocalizationProperties.YouMustBeInAConference] = "You must be in a conference to do this. To join a conference, select one from the Conference menu.";
            _dict[(int) LocalizationProperties.MandrakeRoot] = "Mandrake Root";
            _dict[(int) LocalizationProperties.LoggingIntoShard] = "Logging into Shard";
            _dict[(int) LocalizationProperties.YouAreShowingYourCharName] = "You are now showing your character name to any players who inquire with the whois command.";
            _dict[(int) LocalizationProperties.WindowTitle0] = "ClassicUO - {0}";
            _dict[(int) LocalizationProperties.ThisMayFlagYouCriminal] = "This may flag\nyou criminal!";
            _dict[(int) LocalizationProperties.NotGivenYouSpeakingPrivileges] = "The moderator of this conference has not given you speaking privileges.";
            _dict[(int) LocalizationProperties.Paperdoll] = "Paperdoll";
            _dict[(int) LocalizationProperties.Options] = "Options";
            _dict[(int) LocalizationProperties.YouHaveLeftThe0Channel] = "You have left the '{0}' channel.";
            _dict[(int) LocalizationProperties.YouAreAlreadyIgnoring1] = "You are already ignoring %1.";
            _dict[(int) LocalizationProperties.YouAreAlreadyInTheConference1] = "You are already in the conference '%1'.";
            _dict[(int) LocalizationProperties.IsKnownInTheLandsOfBritanniaAs2] = "%1 is known in the lands of Britannia as %2.";
            _dict[(int) LocalizationProperties.AlwaysRunIsNowOn] = "Always run is now on.";
            _dict[(int) LocalizationProperties.RemovedYourSpeakingPrivileges] = "%1, a conference moderator, has removed your speaking privileges for this conference.";
            _dict[(int) LocalizationProperties.YouWillNoLongerReceivePM] = "You will no longer receive private messages. Those who send you a message will be notified that you are blocking incoming messages.";
            _dict[(int) LocalizationProperties.ClientViewRangeIsNow0] = "ClientViewRange is now {0}.";
            _dict[(int) LocalizationProperties.NotSeeing] = "<not seeing>";
            _dict[(int) LocalizationProperties.ModeratorsWillHaveSpeakingPrivs] = "From now on, only moderators will have speaking privileges in this conference by default.";
            _dict[(int) LocalizationProperties.CraftedBy] = "Crafted by ";
            _dict[(int) LocalizationProperties.AStormIsBrewing] = "A storm is brewing.";
            _dict[(int) LocalizationProperties.ReconnectPleaseWait01] = "Reconnect, please wait...`{0}`\n`{1}`";
            _dict[(int) LocalizationProperties.Increased] = "increased";
            _dict[(int) LocalizationProperties.YouAreNotIgnoring1] = "You are not ignoring %1.";
            _dict[(int) LocalizationProperties.HasMadeYouAConferenceModerator] = "%1 has made you a conference moderator.";
            _dict[(int) LocalizationProperties.GrabBagSet0] = "Grab Bag set: {0}";
            _dict[(int) LocalizationProperties.ScreenshotStoredIn0] = "Screenshot stored in: {0}";
            _dict[(int) LocalizationProperties.GrantedYouSpeakingPrivileges] = "%1, a conference moderator, has granted you speaking privileges in this conference.";
            _dict[(int) LocalizationProperties.YouAreNoLongerIgnoringAnyone] = "You are no longer ignoring anyone.";
            _dict[(int) LocalizationProperties.GraveDust] = "Grave Dust";
            _dict[(int) LocalizationProperties.HasBeenKickedOutOfTheConference] = "%1 has been kicked out of the conference.";
            _dict[(int) LocalizationProperties.Miscellaneous] = "Miscellaneous";
            _dict[(int) LocalizationProperties.Mana] = "Mana";
            _dict[(int) LocalizationProperties.Bard] = "Bard";
            _dict[(int) LocalizationProperties.Ouch] = "Ouch!";
            _dict[(int) LocalizationProperties.Hits] = "Hits";
            _dict[(int) LocalizationProperties.Stam] = "Stam";
            _dict[(int) LocalizationProperties.Invariant] = "Invariant";
            _dict[(int) LocalizationProperties.YourSkillIn0Has1By2ItIsNow3] = "Your skill in {0} has {1} by {2:F1}.  It is now {3:F1}.";
            _dict[(int) LocalizationProperties.ErrorInSynchronization] = "An error has occurred in the synchronization between the login servers and this world.  Please close your client and try again.";
            _dict[(int) LocalizationProperties.ThatCharacterDoesNotExist] = "That character does not exist.";
            _dict[(int) LocalizationProperties.TheIGRTimeLimitHasBeenMet] = "The IGR time limit has been met.";
            _dict[(int) LocalizationProperties.IncorrectNamePassword] = "Incorrect name/password.";
            _dict[(int) LocalizationProperties.GeneralIGRAuthenticationFailure] = "General IGR authentication failure.";
            _dict[(int) LocalizationProperties.ClientCouldNotAttachToServer] = "The client could not attach to the game server. It must have been taken down, please wait a few minutes and try again.";
            _dict[(int) LocalizationProperties.CharacterIsQueuedForBackup] = "That character is currently queued for backup and cannot be deleted.";
            _dict[(int) LocalizationProperties.ThatCharacterIsBeingPlayed] = "That character is being played right now.";
            _dict[(int) LocalizationProperties.ThatItemDoesNotBelongToYou] = "That item does not belong to you.  You'll have to steal it.";
            _dict[(int) LocalizationProperties.ThatIsOutOfSight] = "That is out of sight.";
            _dict[(int) LocalizationProperties.CharacterIsNotOldEnough] = "That character is not old enough to delete. The character must be 7 days old before it can be deleted.";
            _dict[(int) LocalizationProperties.YouAreAlreadyHoldingAnItem] = "You are already holding an item.";
            _dict[(int) LocalizationProperties.AnotherCharacterOnline] = "Another character from this account is currently online in this world.  You must either log in as that character or wait for it to time out.";
            _dict[(int) LocalizationProperties.TheIGRConcurrencyLimitHasBeenMet] = "The IGR concurrency limit has been met.";
            _dict[(int) LocalizationProperties.CharacterTransferInProgress] = "Character transfer in progress.";
            _dict[(int) LocalizationProperties.YourAccountCredentialsAreInvalid] = "Your account credentials are invalid.";
            _dict[(int) LocalizationProperties.IdleTooLong] = "You have been idle for too long.  If you do not do anything in the next minute, you will be logged out.";
            _dict[(int) LocalizationProperties.ThatIsTooFarAway] = "That is too far away.";
            _dict[(int) LocalizationProperties.SomeoneIsAlreadyUsingThisAccount] = "Someone is already using this account.";
            _dict[(int) LocalizationProperties.CharacterPasswordInvalid] = "That character password is invalid.";
            _dict[(int) LocalizationProperties.CommunicationProblem] = "Communication problem.";
            _dict[(int) LocalizationProperties.CouldntCarryOutYourRequest] = "Couldn't carry out your request.";
            _dict[(int) LocalizationProperties.CharacterDoesNotExist] = "This character does not exist anymore.  You will have to recreate it.";
            _dict[(int) LocalizationProperties.YouCanNotPickThatUp] = "You can not pick that up.";
            _dict[(int) LocalizationProperties.IncorrectPassword] = "Incorrect password";
            _dict[(int) LocalizationProperties.ClientPathIsNotAValidUODirectory] = "'{0}' is not a valid UO directory";
            _dict[(int) LocalizationProperties.YourAccountHasBeenBlocked] = "Your account has been blocked.";
            _dict[(int) LocalizationProperties.CharacterAlreadyExists] = "This character already exists.\nPlaying...";
            _dict[(int) LocalizationProperties.CouldntConnectToUO] = "Couldn't connect to Ultima Online.  Please try again in a few moments.";
            _dict[(int) LocalizationProperties.CouldNotAttachServer] = "Could not attach to game server.";
            _dict[(int) LocalizationProperties.ManaCost0MinSkill1] = "Mana cost: {0}\nMin. Skill: {1}";
            _dict[(int) LocalizationProperties.UseLargeContainersGump] = "Use large containers gump";
            _dict[(int) LocalizationProperties.Stamina] = "Stamina";
            _dict[(int) LocalizationProperties.BackpackStyle] = "Select Character Backpack Style";
            _dict[(int) LocalizationProperties.ShowGroupHealthbar] = "Show group healthbar";
            _dict[(int) LocalizationProperties.SetsLightLevelToMax] = "Sets light level to max but still renders lights";
            _dict[(int) LocalizationProperties.MapMarkerOptions] = "Map Marker Options";
            _dict[(int) LocalizationProperties.CorpseOpenOptions] = "Corpse Open Options:";
            _dict[(int) LocalizationProperties.GamePlayWindowSize] = "Game Play Window Size: ";
            _dict[(int) LocalizationProperties.HitChanceIncrease] = "Hit Chance Increase";
            _dict[(int) LocalizationProperties.MurdererColor] = "Murderer Color";
            _dict[(int) LocalizationProperties.UseShiftEnterToSendMessage] = "Use `Shift+Enter` to send message without closing chat";
            _dict[(int) LocalizationProperties.PartyName0Text1] = "[Party][{0}]: {1}";
            _dict[(int) LocalizationProperties.NamesHealthbars] = "Names & Healthbars";
            _dict[(int) LocalizationProperties.Brighlight] = "- Brighlight:";
            _dict[(int) LocalizationProperties.HighlightObjects] = "Highlight game objects";
            _dict[(int) LocalizationProperties.CloseHPGumpWhen] = "Close healthbar gump when:";
            _dict[(int) LocalizationProperties.ThereIsNoOneInThatPartySlot] = "There is no one in that party slot.";
            _dict[(int) LocalizationProperties.EyedropperTool] = "Eyedropper Tool";
            _dict[(int) LocalizationProperties.NextPage] = "Next Page";
            _dict[(int) LocalizationProperties.HPFields_Static] = "Static fields";
            _dict[(int) LocalizationProperties.CustomColorAuraForPartyMembers] = "Custom color aura for party members";
            _dict[(int) LocalizationProperties.ResetGroups] = "Reset groups";
            _dict[(int) LocalizationProperties.MarkCaveTiles] = "Mark cave tiles";
            _dict[(int) LocalizationProperties.Whisper] = "[Whisper]: ";
            _dict[(int) LocalizationProperties.HideRoofTiles] = "Hide roof tiles";
            _dict[(int) LocalizationProperties.SecondaryAbilityIcon] = "Secondary Ability Icon";
            _dict[(int) LocalizationProperties.BlackWhiteModeForDeadPlayer] = "Black & White mode for dead player";
            _dict[(int) LocalizationProperties.SelectWhichShardToPlayOn] = "Select which shard to play on:";
            _dict[(int) LocalizationProperties.CounterLayout] = "Counter Layout:";
            _dict[(int) LocalizationProperties.InnocentColor] = "Innocent Color";
            _dict[(int) LocalizationProperties.Containers] = "Containers";
            _dict[(int) LocalizationProperties.GridLoot_GridOnly] = "Grid loot only";
            _dict[(int) LocalizationProperties.DelayBeforeDisplay] = "Delay before display:";
            _dict[(int) LocalizationProperties.RaiseRoofPlacementLevel] = "Raise Roof Placement Level";
            _dict[(int) LocalizationProperties.NetStats] = "NetStats";
            _dict[(int) LocalizationProperties.AuraUnderFeet] = "Aura under feet";
            _dict[(int) LocalizationProperties.Accept] = "Accept";
            _dict[(int) LocalizationProperties.Author] = "Author:";
            _dict[(int) LocalizationProperties.Female] = "F";
            _dict[(int) LocalizationProperties.PoisonedColor] = "Poisoned Color";
            _dict[(int) LocalizationProperties.TextColor] = "Text color";
            _dict[(int) LocalizationProperties.Floors] = "Floors";
            _dict[(int) LocalizationProperties.Static0Height1Flags2Alpha3] = "Static (0x{0:X4})  height: {1}  flags: {2}  Alpha: {3}";
            _dict[(int) LocalizationProperties.CircleTransType_Full] = "Full";
            _dict[(int) LocalizationProperties.CellSize] = "Cell size:";
            _dict[(int) LocalizationProperties.FilterTypeFormatON] = "{0} [{1}]";
            _dict[(int) LocalizationProperties.Damage] = "Damage";
            _dict[(int) LocalizationProperties.Delete] = "Delete";
            _dict[(int) LocalizationProperties.NewMacro] = "New macro";
            _dict[(int) LocalizationProperties.NewGroup] = "New Group";
            _dict[(int) LocalizationProperties.CUOVersion0] = "ClassicUO Version {0}";
            _dict[(int) LocalizationProperties.Macros] = "Macros";
            _dict[(int) LocalizationProperties.ShopGumpSize] = "Shop Gump Size (multiple of 60):";
            _dict[(int) LocalizationProperties.FontStyle] = "Font Style";
            _dict[(int) LocalizationProperties.BackpackStyle_GhoulSkin] = "GhoulSkin";
            _dict[(int) LocalizationProperties.AutoOpenDoors] = "Auto Open Doors";
            _dict[(int) LocalizationProperties.CanAttackColor] = "Can Be Attacked Color";
            _dict[(int) LocalizationProperties.Backup] = "Backup";
            _dict[(int) LocalizationProperties.PoisonResistance] = "Poison Resistance";
            _dict[(int) LocalizationProperties.Dexterity] = "Dexterity";
            _dict[(int) LocalizationProperties.LoginMusic] = "Login music";
            _dict[(int) LocalizationProperties.Commit] = "Commit";
            _dict[(int) LocalizationProperties.SmoothBoat] = "Smooth boat movements";
            _dict[(int) LocalizationProperties.Create] = "Create";
            _dict[(int) LocalizationProperties.ScaleItemsInsideContainers] = "Scale items inside containers";
            _dict[(int) LocalizationProperties.HideChatGradient] = "Hide Chat Gradient";
            _dict[(int) LocalizationProperties.SendThePartyAMessage] = "Send the party a message";
            _dict[(int) LocalizationProperties.TopBarGumpAlreadyExists] = "TopBarGump already exists!!";
            _dict[(int) LocalizationProperties.SwingSpeedIncrease] = "Swing Speed Increase";
            _dict[(int) LocalizationProperties.Intelligence] = "Intelligence";
            _dict[(int) LocalizationProperties.FilterType] = "Filter type [TEST]:";
            _dict[(int) LocalizationProperties.SaveJournalToFileInGameFolder] = "Save Journal to file in game folder";
            _dict[(int) LocalizationProperties.MacroName] = "Macro name:";
            _dict[(int) LocalizationProperties.NoName] = "No Name";
            _dict[(int) LocalizationProperties.PartyMessageColor] = "Party Message Color";
            _dict[(int) LocalizationProperties.TooltipFontSelect] = "Tooltip font!";
            _dict[(int) LocalizationProperties.TextAlphaFading] = "Text alpha fading";
            _dict[(int) LocalizationProperties.QueryAttack] = "Query before attack";
            _dict[(int) LocalizationProperties.ShowGumpPartyInv] = "Show gump for party invites";
            _dict[(int) LocalizationProperties.BackpackStyle_Default] = "Default";
            _dict[(int) LocalizationProperties.TimeLeft] = "{0}\nTime left: {1:00}:{2:00}:{3:00}";
            _dict[(int) LocalizationProperties.DragHumanoidsOnly] = "Select humanoids only";
            _dict[(int) LocalizationProperties.HPType_MobileDead] = "Mobile is dead";
            _dict[(int) LocalizationProperties.MobilesAndCorpsesOnly] = "Mobiles and Corpses only";
            _dict[(int) LocalizationProperties.General] = "General";
            _dict[(int) LocalizationProperties.Activated] = "Activated";
            _dict[(int) LocalizationProperties.Abilities] = "Abilities";
            _dict[(int) LocalizationProperties.DarkMode] = "Dark mode";
            _dict[(int) LocalizationProperties.TerrainShadowsLevel] = "Terrain shadows level:";
            _dict[(int) LocalizationProperties.GamePlayWindowPosition] = "Game Play Window Position: ";
            _dict[(int) LocalizationProperties.P0HasInvitedYouToParty] = "{0} has invited you to join a party.";
            _dict[(int) LocalizationProperties.Span0Hours] = "+{0}hr";
            _dict[(int) LocalizationProperties.OutOfRange] = "<out of range>";
            _dict[(int) LocalizationProperties.EnableAbbreviatedAmountCountrs] = "Enable abbreviated amount values\nwhen amount is or exceeds";
            _dict[(int) LocalizationProperties.FasterCastRecovery] = "Faster Cast Recovery";
            _dict[(int) LocalizationProperties.WorldMapMarkersLoaded0] = "WorldMap markers loaded ({0})";
            _dict[(int) LocalizationProperties.MacroDeleteConfirmation] = "Do you want\ndelete it?";
            _dict[(int) LocalizationProperties.InvalidLocation] = "Invalid location entered: Enter \"X Y\" or \"0°0'N,0°0'W\"";
            _dict[(int) LocalizationProperties.SaveExistingChanges] = "Save existing changes and finalize design.";
            _dict[(int) LocalizationProperties.GuildName0Text1] = "[Guild][{0}]: {1}";
            _dict[(int) LocalizationProperties.SpellOverheadFormat] = "Spell Overhead format: ({power} for powerword - {spell} for spell name)";
            _dict[(int) LocalizationProperties.UseAdditionalButtonsToActivateChat] = "Use additional buttons to activate chat: ! ; : / \\ , . [ | -";
            _dict[(int) LocalizationProperties.TargetContainerToGrabItemsInto] = "Target the container to Grab items into.";
            _dict[(int) LocalizationProperties.DateTime] = "Date/Time";
            _dict[(int) LocalizationProperties.Shadows] = "Shadows";
            _dict[(int) LocalizationProperties.Revert] = "Revert";
            _dict[(int) LocalizationProperties.TreesStumps] = "Trees to stumps";
            _dict[(int) LocalizationProperties.Remove] = "Remove";
            _dict[(int) LocalizationProperties.YellColor] = "Yell Color";
            _dict[(int) LocalizationProperties.Followers] = "Followers";
            _dict[(int) LocalizationProperties.HighlightRedWhenBelow] = "Highlight red when amount is below";
            _dict[(int) LocalizationProperties.AuraOnMouseTarget] = "Aura on mouse target";
            _dict[(int) LocalizationProperties.Minimize] = "Minimize";
            _dict[(int) LocalizationProperties.Stairs] = "Stairs";
            _dict[(int) LocalizationProperties.Style0] = "Style {0}";
            _dict[(int) LocalizationProperties.Speech] = "Speech";
            _dict[(int) LocalizationProperties.Alliance] = "[Alliance]: ";
            _dict[(int) LocalizationProperties.MobilesOnly] = "Mobiles only";
            _dict[(int) LocalizationProperties.SortBy] = "Sort by:";
            _dict[(int) LocalizationProperties.Sounds] = "Sounds";
            _dict[(int) LocalizationProperties.ShowHP] = "Show HP";
            _dict[(int) LocalizationProperties.RelativeDragAndDropContainers] = "Relative drag and drop items in containers";
            _dict[(int) LocalizationProperties.CorpseOpt_None] = "None";
            _dict[(int) LocalizationProperties.CorpseOpt_Both] = "Both";
            _dict[(int) LocalizationProperties.HPFields_Normal] = "Normal fields";
            _dict[(int) LocalizationProperties.SpellFormat_Default] = "{power} [{spell}]";
            _dict[(int) LocalizationProperties.Upkeep0Mana1MinSkill2] = "Upkeep Cost: {0}\nMana cost: {0}\nMin. Skill: {0}";
            _dict[(int) LocalizationProperties.HarmfulSpellHue] = "Harmful Spell Hue";
            _dict[(int) LocalizationProperties.TooltipFontHue] = "Tooltip font hue";
            _dict[(int) LocalizationProperties.AltCloseGumps] = "Hold ALT key + right click to close Anchored gumps";
            _dict[(int) LocalizationProperties.Unicode] = "Unicode";
            _dict[(int) LocalizationProperties.Land0Flags1] = "Land (0x{0:X4})  flags: {1}";
            _dict[(int) LocalizationProperties.AllianceMessageColor] = "Alliance Message Color";
            _dict[(int) LocalizationProperties.IndexOutOfbounds] = "Index outbounds when parsing counter bar items";
            _dict[(int) LocalizationProperties.PartyManifest] = "Party Manifest";
            _dict[(int) LocalizationProperties.KeyMod_Shift] = "Shift";
            _dict[(int) LocalizationProperties.Strength] = "Strength";
            _dict[(int) LocalizationProperties.LoadingWorldMapMarkers] = "Loading WorldMap markers..";
            _dict[(int) LocalizationProperties.ItemsOnly] = "Items only";
            _dict[(int) LocalizationProperties.ShowYourName] = "Show your name";
            _dict[(int) LocalizationProperties.ColdResistance] = "Cold Resistance";
            _dict[(int) LocalizationProperties.Journal] = "Journal";
            _dict[(int) LocalizationProperties.Command] = "[Command]: ";
            _dict[(int) LocalizationProperties.AlwaysRunHidden] = "Unless hidden";
            _dict[(int) LocalizationProperties.ContLoc_TopRight] = "Top right";
            _dict[(int) LocalizationProperties.ContainerScale] = "- Container scale:";
            _dict[(int) LocalizationProperties.ShowMarkerIcons] = "Show marker icons";
            _dict[(int) LocalizationProperties.ShowMarkerNames] = "Show marker names";
            _dict[(int) LocalizationProperties.Password] = "Password";
            _dict[(int) LocalizationProperties.Tooltip] = "Tooltip";
            _dict[(int) LocalizationProperties.TopMost] = "Keep map on top";
            _dict[(int) LocalizationProperties.DisableMessageHistory] = "Disable Ctrl + Q/W (messageHistory)";
            _dict[(int) LocalizationProperties.AlwaysUseFullsizeGameWindow] = "Always use fullsize game window";
            _dict[(int) LocalizationProperties.HPType_MobileOOR] = "Mobile out of range";
            _dict[(int) LocalizationProperties.AddNewMember] = "Add New Member";
            _dict[(int) LocalizationProperties.ShowTarRangeIndic] = "Show target range indicator";
            _dict[(int) LocalizationProperties.AuraType_Warmode] = "Warmode";
            _dict[(int) LocalizationProperties.WhisperColor] = "Whisper Color";
            _dict[(int) LocalizationProperties.UseColoredLights] = "Use colored lights";
            _dict[(int) LocalizationProperties.EnableCounters] = "Enable Counters";
            _dict[(int) LocalizationProperties.ShowYourCoordinates] = "Show your coordinates";
            _dict[(int) LocalizationProperties.OutOfRangeColor] = "No color for object out of range";
            _dict[(int) LocalizationProperties.ShowBuffDuration] = "Show buff duration";
            _dict[(int) LocalizationProperties.YouMustHaveThreeUniqueSkillsChosen] = "You must have three unique skills chosen!";
            _dict[(int) LocalizationProperties.Passive] = "Passive";
            _dict[(int) LocalizationProperties.SmoothDoors] = "Smooth doors";
            _dict[(int) LocalizationProperties.EmoteColor] = "Emote Color";
            _dict[(int) LocalizationProperties.PartyCanLootMe] = "Party can loot me";
            _dict[(int) LocalizationProperties.HPShow_Less] = "Less than 100 %";
            _dict[(int) LocalizationProperties.HighlightOnUse] = "Highlight On Use";
            _dict[(int) LocalizationProperties.ShowHousesContent] = "Show houses content";
            _dict[(int) LocalizationProperties.ContLoc_RememberEveryContainer] = "Remember every container";
            _dict[(int) LocalizationProperties.ChatMessageColor] = "Chat Message Color";
            _dict[(int) LocalizationProperties.PlayFootsteps] = "Play Footsteps";
            _dict[(int) LocalizationProperties.Decline] = "Decline";
            _dict[(int) LocalizationProperties.DisbandTheParty] = "Disband the party";
            _dict[(int) LocalizationProperties.LowerReagentCost] = "Lower Reagent Cost";
            _dict[(int) LocalizationProperties.WeaponDamageIncrease] = "Weapon Damage Increase";
            _dict[(int) LocalizationProperties.GlobalChat] = "Global Chat";
            _dict[(int) LocalizationProperties.Localisation] = "Localisation";
            _dict[(int) LocalizationProperties.TextOverheadType0Hue1] = "TextOverhead type: {0}  hue: 0x{1:X4}";
            _dict[(int) LocalizationProperties.ShowAllMarkers] = "Show all markers";
            _dict[(int) LocalizationProperties.Experimental] = "Experimental";
            _dict[(int) LocalizationProperties.HPType_None] = "None";
            _dict[(int) LocalizationProperties.PreviousPage] = "PreviousPage";
            _dict[(int) LocalizationProperties.ImpossibleToDefineTheClientVersion0] = "Impossible to define the client version.\nClient version: '{0}'";
            _dict[(int) LocalizationProperties.RevertYourDesign] = "Revert your design in progress to match your currently visible, finalized design.";
            _dict[(int) LocalizationProperties.ShiftContext] = "Hold Shift for Context Menus";
            _dict[(int) LocalizationProperties.NoOneHasInvitedYouToBeInAParty] = "No one has invited you to be in a party.";
            _dict[(int) LocalizationProperties.LowerRoofPlacementLevel] = "Lower Roof Placement Level";
            _dict[(int) LocalizationProperties.OverrideContainerGumpLocation] = "Override container gump location";
            _dict[(int) LocalizationProperties.UseObject] = "Use object (Double click)";
            _dict[(int) LocalizationProperties.FriendColor] = "Friend Color";
            _dict[(int) LocalizationProperties.EnableOverheadSpellHue] = "Enable Overhead Spell Hue";
            _dict[(int) LocalizationProperties.EnablePathfinding] = "Enable pathfinding";
            _dict[(int) LocalizationProperties.ContLoc_NearContainerPosition] = "Near container position";
            _dict[(int) LocalizationProperties.ShiftStack] = "Hold Shift to split stack of items";
            _dict[(int) LocalizationProperties.ShowStatsChangedMessage] = "Inform when stats change";
            _dict[(int) LocalizationProperties.UseCustomHPBars] = "Use custom healthbars gump";
            _dict[(int) LocalizationProperties.ReleasingCtrlRestoresScale] = "Releasing Ctrl Restores Scale";
            _dict[(int) LocalizationProperties.By] = "by";
            _dict[(int) LocalizationProperties.ON] = "ON";
            _dict[(int) LocalizationProperties.RE] = "RE: ";
            _dict[(int) LocalizationProperties.FPSInactive] = "Reduce FPS when game is inactive";
            _dict[(int) LocalizationProperties.SpeechFont] = "Speech font:";
            _dict[(int) LocalizationProperties.ShowGroupName] = "Show group name";
            _dict[(int) LocalizationProperties.DoubleClickLootContainers] = "Double click to loot items inside containers";
            _dict[(int) LocalizationProperties.BeneficSpellHue] = "Benefic Spell Hue";
            _dict[(int) LocalizationProperties.UseXBREffectBETA] = "Use xBR effect [BETA]";
            _dict[(int) LocalizationProperties.GlobalChatNotImplementedYet] = "GlobalChat not implemented yet.";
            _dict[(int) LocalizationProperties.HPFields_Tile] = "Tile fields";
            _dict[(int) LocalizationProperties.UseBlackBackgr] = "Opaque background";
            _dict[(int) LocalizationProperties.LeaveTheParty] = "Leave the party";
            _dict[(int) LocalizationProperties.SaveAccount] = "Save Account";
            _dict[(int) LocalizationProperties.ShowHousesBoats] = "Show houses/boats";
            _dict[(int) LocalizationProperties.HP_Percentage] = "Percentage";
            _dict[(int) LocalizationProperties.FreeView] = "Free view";
            _dict[(int) LocalizationProperties.TooltipZoom] = "Tooltip zoom:";
            _dict[(int) LocalizationProperties.TooltipFont] = "Tooltip font:";
            _dict[(int) LocalizationProperties.ReloadMarkers] = "Reload markers";
            _dict[(int) LocalizationProperties.ShowCaps] = " - Show Caps";
            _dict[(int) LocalizationProperties.ShowReal] = " - Show Real";
            _dict[(int) LocalizationProperties.Add] = "Add";
            _dict[(int) LocalizationProperties.All] = "All";
            _dict[(int) LocalizationProperties.FPS] = "- FPS:";
            _dict[(int) LocalizationProperties.Dex] = "Dex";
            _dict[(int) LocalizationProperties.Map] = "Map";
            _dict[(int) LocalizationProperties.Cap] = "Cap";
            _dict[(int) LocalizationProperties.OFF] = "OFF";
            _dict[(int) LocalizationProperties.Sex] = "Sex";
            _dict[(int) LocalizationProperties.NoteToSelf0] = "Note to self: {0}";
            _dict[(int) LocalizationProperties.Emote] = "[Emote]: ";
            _dict[(int) LocalizationProperties.Erase] = "Erase";
            _dict[(int) LocalizationProperties.SpellDamageIncrease] = "Spell Damage Increase";
            _dict[(int) LocalizationProperties.Armor] = "Armor";
            _dict[(int) LocalizationProperties.Fonts] = "Fonts";
            _dict[(int) LocalizationProperties.ASCII] = "ASCII";
            _dict[(int) LocalizationProperties.TellEmpty] = "[Tell] []: ";
            _dict[(int) LocalizationProperties.Guild] = "[Guild]: ";
            _dict[(int) LocalizationProperties.Debug] = "Debug";
            _dict[(int) LocalizationProperties.Doors] = "Doors";
            _dict[(int) LocalizationProperties.Music] = "Music";
            _dict[(int) LocalizationProperties.Buffs] = "Buffs";
            _dict[(int) LocalizationProperties.Color] = "Color";
            _dict[(int) LocalizationProperties.Clear] = "Clear";
            _dict[(int) LocalizationProperties.LoginToUO] = "Log in to Ultima Online";
            _dict[(int) LocalizationProperties.RestoreYourDesign] = "Restore your design in progress to a design you have previously backed up.";
            _dict[(int) LocalizationProperties.BorderlessWindow] = "Borderless window";
            _dict[(int) LocalizationProperties.Index] = "INDEX";
            _dict[(int) LocalizationProperties.Label] = "Label";
            _dict[(int) LocalizationProperties.Leave] = "Leave";
            _dict[(int) LocalizationProperties.Video] = "Video";
            _dict[(int) LocalizationProperties.Walls] = "Walls";
            _dict[(int) LocalizationProperties.Tell0] = "[Tell] [{0}]: ";
            _dict[(int) LocalizationProperties.Title] = "Title:";
            _dict[(int) LocalizationProperties.Total] = "Total: ";
            _dict[(int) LocalizationProperties.Roofs] = "Roofs";
            _dict[(int) LocalizationProperties.Sound] = "Sound";
            _dict[(int) LocalizationProperties.Party] = "[Party]: ";
            _dict[(int) LocalizationProperties.YouAreNotInAParty] = "You are not in a party.";
            _dict[(int) LocalizationProperties.HideVegetation] = "Hide vegetation";
            _dict[(int) LocalizationProperties.EnableDeathScreen] = "Enable Death Screen";
            _dict[(int) LocalizationProperties.SystemMenu] = "System Menu";
            _dict[(int) LocalizationProperties.NeutralSpellHue] = "Neutral Spell Hue";
            _dict[(int) LocalizationProperties.Selected0] = "- Selected: {0}";
            _dict[(int) LocalizationProperties.LinearClamp] = "Linear Clamp";
            _dict[(int) LocalizationProperties.AddItem] = "+ Add item";
            _dict[(int) LocalizationProperties.CombatSpells] = "Combat-Spells";
            _dict[(int) LocalizationProperties.Account] = "Account Name";
            _dict[(int) LocalizationProperties.PhysicalResistance] = "Physical Resistance";
            _dict[(int) LocalizationProperties.DragKey] = "Drag-select modifier key";
            _dict[(int) LocalizationProperties.KeyMod_None] = "None";
            _dict[(int) LocalizationProperties.KeyMod_Ctrl] = "Ctrl";
            _dict[(int) LocalizationProperties.AltMoveGumps] = "Hold ALT key to move gumps";
            _dict[(int) LocalizationProperties.MaxStats] = "Max Stats";
            _dict[(int) LocalizationProperties.ThatSClassicUO] = "That's ClassicUO!";
            _dict[(int) LocalizationProperties.SpeechColor] = "Speech Color";
            _dict[(int) LocalizationProperties.NoMapFiles] = "No map files";
            _dict[(int) LocalizationProperties.CircleTransType_Gradient] = "Gradient";
            _dict[(int) LocalizationProperties.ContLoc_LastDraggedPosition] = "Last dragged position";
            _dict[(int) LocalizationProperties.ThisKeyCombinationAlreadyExists] = "This key combination\nalready exists. Combination used by: {0}";
            _dict[(int) LocalizationProperties.RebuildContainers] = "Rebuild containers.txt";
            _dict[(int) LocalizationProperties.CorpseOpt_NotTar] = "Not Targeting";
            _dict[(int) LocalizationProperties.CorpseOpt_NotHid] = "Not Hiding";
            _dict[(int) LocalizationProperties.SaveHPBarsOnLogout] = "Save healthbars on logout";
            _dict[(int) LocalizationProperties.EnableOverheadSpellFormat] = "Enable Overhead Spell Format";
            _dict[(int) LocalizationProperties.UseTooltip] = "Use tooltip";
            _dict[(int) LocalizationProperties.UOStore] = "UOStore";
            _dict[(int) LocalizationProperties.PartyAuraColor] = "Party Aura Color";
            _dict[(int) LocalizationProperties.ReproduceSoundsAndMusic] = "Reproduce sounds and music when ClassicUO is not focused";
            _dict[(int) LocalizationProperties.Reagents] = "Reagents:";
            _dict[(int) LocalizationProperties.KeyCombinationAlreadyExists] = "Key combination already exists.";
            _dict[(int) LocalizationProperties.BookPage0TooManyLines1Lost] = "Book page {0} split into too many lines: {1} Additional lines will be lost";
            _dict[(int) LocalizationProperties.WindowToggle] = "Window Toggle";
            _dict[(int) LocalizationProperties.AlwaysRun] = "Always run";
            _dict[(int) LocalizationProperties.TooltipBackgroundOpacity] = "Tooltip background opacity:";
            _dict[(int) LocalizationProperties.PartyCannotLootMe] = "Party CANNOT loot me";
            _dict[(int) LocalizationProperties.CombatMusic] = "Combat music";
            _dict[(int) LocalizationProperties.Counter_Rows] = "Rows:";
            _dict[(int) LocalizationProperties.HitPoints] = "Hit Points";
            _dict[(int) LocalizationProperties.ActiveChatWhenPressingEnter] = "Active chat when pressing ENTER";
            _dict[(int) LocalizationProperties.Autologin] = "Autologin";
            _dict[(int) LocalizationProperties.YourCurrentChannel] = "Your current channel:";
            _dict[(int) LocalizationProperties.ClickCloseAllGumps] = "Close all Anchored gumps when right click on a group";
            _dict[(int) LocalizationProperties.CastSpellsByOneClick] = "Cast spells by one click";
            _dict[(int) LocalizationProperties.RunMouseInASeparateThread] = "Run mouse in a separate thread";
            _dict[(int) LocalizationProperties.TithingPointsAvailable] = "Tithing points\nAvailable: ";
            _dict[(int) LocalizationProperties.ShadowStatics] = "Show tree and rock shadows";
            _dict[(int) LocalizationProperties.BackpackStyle_PolarBear] = "PolarBear";
            _dict[(int) LocalizationProperties.LockGameWindowMovingResizing] = "Lock game window moving/resizing";
            _dict[(int) LocalizationProperties.YouAreNotPartyLeader] = "You are not party leader.";
            _dict[(int) LocalizationProperties.CreateMacroButton] = "+ Create macro button";
            _dict[(int) LocalizationProperties.ChooseName] = "You are about to choose your name for the Ultima Online chat system. This name will be PERMANENT and unique on this shard. It will apply to all characters using this account. Do not use your Ultima Online account name for this name as the name you choose will be public. Enter your chat name here:";
            _dict[(int) LocalizationProperties.ShowIncCorpses] = "Show incoming new corpses";
            _dict[(int) LocalizationProperties.QueryBeneficialActs] = "Query before performing beneficial acts on\nMurderers, Criminals, Grays (Monsters/Animals)";
            _dict[(int) LocalizationProperties.Paperdoll] = "Paperdoll";
            _dict[(int) LocalizationProperties.ChangingLanguageNeedsRestartToTakeEffect] = "Changing language needs restart to take effect";
            _dict[(int) LocalizationProperties.ColoredBars] = "Colored bars";
            _dict[(int) LocalizationProperties.FireResistance] = "Fire Resistance";
            _dict[(int) LocalizationProperties.SetLootBag] = "Set loot bag";
            _dict[(int) LocalizationProperties.DarkNights] = "Dark nights";
            _dict[(int) LocalizationProperties.GuildMessageColor] = "Guild Message Color";
            _dict[(int) LocalizationProperties.ClearAllChanges] = "Clear all changes, returning your design in progress to a blank foundation.";
            _dict[(int) LocalizationProperties.Counter_Columns] = "Columns:";
            _dict[(int) LocalizationProperties.DisableMenu] = "Disable the Menu Bar";
            _dict[(int) LocalizationProperties.GameEffect] = "GameEffect";
            _dict[(int) LocalizationProperties.UseOldStatusGump] = "Use old status gump";
            _dict[(int) LocalizationProperties.DisableArrowsPlayerMovement] = "Disable arrows & numlock arrows (player moving)";
            _dict[(int) LocalizationProperties.CorpseOpenRange] = "Corpse Open Range:";
            _dict[(int) LocalizationProperties.HPShow_Smart] = "Smart";
            _dict[(int) LocalizationProperties.ChatButtonPushedNotImplementedYet] = "Chat button pushed! Not implemented yet!";
            _dict[(int) LocalizationProperties.Item0Price1] = "{0} at {1}gp";
            _dict[(int) LocalizationProperties.PermanentlyDelete0] = "Permanently delete character \"{0}\n\"?";
            _dict[(int) LocalizationProperties.GotoLocation] = "Go to location";
            _dict[(int) LocalizationProperties.ResizeGameWindow] = "Resize game window";
            _dict[(int) LocalizationProperties.ObjectInformation] = "Object Information";
            _dict[(int) LocalizationProperties.Restore] = "Restore";
            _dict[(int) LocalizationProperties.Latency] = "Latency:";
            _dict[(int) LocalizationProperties.Counters] = "Counters";
            _dict[(int) LocalizationProperties.ObjAlphaFading] = "Objects alpha fading";
            _dict[(int) LocalizationProperties.HideScreenshotStoredInMessage] = "Hide \"Screenshot stored in\" message";
            _dict[(int) LocalizationProperties.HighlighState] = "Highlight by state (poisoned, yellow hits, paralyzed)";
            _dict[(int) LocalizationProperties.EnterLocation] = "Enter X Y location:";
            _dict[(int) LocalizationProperties.OverrideGameFont] = "Override game font";
            _dict[(int) LocalizationProperties.ShowIncMobiles] = "Show incoming new mobiles";
            _dict[(int) LocalizationProperties.AuraType_CtrlShift] = "Ctrl+Shift";
            _dict[(int) LocalizationProperties.InvulColor] = "Invulnerable Color";
            _dict[(int) LocalizationProperties.AuraType_None] = "None";
            _dict[(int) LocalizationProperties.EnableCircleTrans] = "Enable circle of transparency";
            _dict[(int) LocalizationProperties.HighlightContainerWhenSelected] = "Highlight container on ground when mouse is over a container gump";
            _dict[(int) LocalizationProperties.TabCombat] = "Hold TAB key for combat";
            _dict[(int) LocalizationProperties.DataHighlightType] = "Data highlight type:";
            _dict[(int) LocalizationProperties.ShowMobiles] = "Show mobiles";
            _dict[(int) LocalizationProperties.DisableClickAutomove] = "Disable Right+Left Click Automove";
            _dict[(int) LocalizationProperties.HP_Both] = "Both";
            _dict[(int) LocalizationProperties.HP_Line] = "Line";
            _dict[(int) LocalizationProperties.HP_Mode] = "mode:";
            _dict[(int) LocalizationProperties.WorldMapLoading] = "WorldMap loading...";
            _dict[(int) LocalizationProperties.Channels] = "Channels";
            _dict[(int) LocalizationProperties.EnableDragHPBars] = "Enable drag-select to open health bars";
            _dict[(int) LocalizationProperties.SallosEasyGrab] = "Sallos easy grab";
            _dict[(int) LocalizationProperties.HPShow_Always] = "Always";
            _dict[(int) LocalizationProperties.WorldMapLoaded] = "WorldMap loaded!";
            _dict[(int) LocalizationProperties.EnergyResistance] = "Energy Resistance";
            _dict[(int) LocalizationProperties.ForceUnicodeInJournal] = "Force Unicode in journal";
            _dict[(int) LocalizationProperties.PacketLoss] = "Packet Loss:";
            _dict[(int) LocalizationProperties.CircleTransType] = "Transparency type:";
            _dict[(int) LocalizationProperties.LowerManaCost] = "Lower Mana Cost";
            _dict[(int) LocalizationProperties.InfoBar] = "Info Bar";
            _dict[(int) LocalizationProperties.GridLoot] = "Grid loot";
            _dict[(int) LocalizationProperties.CreateAChannel] = "Create a channel:";
            _dict[(int) LocalizationProperties.ScaleSpeechDelay] = "Scale speech delay";
            _dict[(int) LocalizationProperties.RandomizeSpeechHues] = "Randomize speech hues";
            _dict[(int) LocalizationProperties.GridLoot_None] = "None";
            _dict[(int) LocalizationProperties.GridLoot_Both] = "Both";
            _dict[(int) LocalizationProperties.HPFields] = "Fields: ";
            _dict[(int) LocalizationProperties.SynchronizeDesignStateWithServer] = "Synchronize design state with server.";
            _dict[(int) LocalizationProperties.Store0Visibility] = "Story {0} Visibility";
            _dict[(int) LocalizationProperties.BackpackStyle_Suede] = "Suede";
            _dict[(int) LocalizationProperties.PrimaryAbilityIcon] = "Primary Ability Icon";
            _dict[(int) LocalizationProperties.ShowSkillsChangedMessageBy] = "Inform when skills change by";
            _dict[(int) LocalizationProperties.AlternativeLights] = "Alternative lights";
            _dict[(int) LocalizationProperties.EnemyColor] = "Enemy Color";
            _dict[(int) LocalizationProperties.SaveClose] = "Save & Close";
            _dict[(int) LocalizationProperties.AllianceName0Text1] = "[Alliance][{0}]: {1}";
            _dict[(int) LocalizationProperties.BookPage0LineTooLong1] = "Book page {0} single line too LONG, total lenght -> {1} vs MAX 79 bytes allowed, some content might get lost";
            _dict[(int) LocalizationProperties.ParalyzedColor] = "Paralyzed Color";
            _dict[(int) LocalizationProperties.AuraType_Always] = "Always";
            _dict[(int) LocalizationProperties.WorldMap] = "World Map";
            _dict[(int) LocalizationProperties.NoCityFound] = "No city found. Something wrong with the received cities.";
            _dict[(int) LocalizationProperties.DeleteMacro] = "Delete macro";
            _dict[(int) LocalizationProperties.ShowYourHealthbar] = "Show your healthbar";
            _dict[(int) LocalizationProperties.EnableMouseWheelForZoom] = "Enable mousewheel for in game zoom scaling (Ctrl + Scroll)";
            _dict[(int) LocalizationProperties.MaximumStats] = "Maximum Stats";
            _dict[(int) LocalizationProperties.SkipEmptyCorpses] = "Skip empty corpses";
            _dict[(int) LocalizationProperties.CriminalColor] = "Criminal Color";
            _dict[(int) LocalizationProperties.QueryBeneficialActs_Tooltip] = "Query before beneficial criminal action";
            _dict[(int) LocalizationProperties.Inventory] = "Inventory";
            _dict[(int) LocalizationProperties.CorpseIsEmpty] = "[GridLoot]: Corpse is empty!";
            _dict[(int) LocalizationProperties.AutoOpenCorpses] = "Auto Open Corpses";
            _dict[(int) LocalizationProperties.ToCustomHouseManagerCategory] = "To _customHouseManager.Category";
            _dict[(int) LocalizationProperties.DefaultZoom] = "Default zoom:";
            _dict[(int) LocalizationProperties.ShowHide0] = "Show/Hide '{0}'";
            _dict[(int) LocalizationProperties.DisableDefaultUOHotkeys] = "Disable default UO hotkeys";
            _dict[(int) LocalizationProperties.ShiftPathfinding] = "Use SHIFT for pathfinding";
            _dict[(int) LocalizationProperties.StandardSkillGump] = "Use standard skills gump";
            _dict[(int) LocalizationProperties.GoToStory0] = "Go To Story {0}";
            _dict[(int) LocalizationProperties.Miscellaneous] = "Miscellaneous";
            _dict[(int) LocalizationProperties.ShowInfoBar] = "Show Info Bar";
            _dict[(int) LocalizationProperties.Gold] = "Gold";
            _dict[(int) LocalizationProperties.Date] = "Date:";
            _dict[(int) LocalizationProperties.Data] = "Data";
            _dict[(int) LocalizationProperties.Dump] = "Dump";
            _dict[(int) LocalizationProperties.Male] = "M";
            _dict[(int) LocalizationProperties.Base] = "Base";
            _dict[(int) LocalizationProperties.Cost] = "Cost";
            _dict[(int) LocalizationProperties.Chat] = "Chat";
            _dict[(int) LocalizationProperties.Info] = "< ? >";
            _dict[(int) LocalizationProperties.Name] = "Name:";
            _dict[(int) LocalizationProperties.Next] = ">>";
            _dict[(int) LocalizationProperties.Luck] = "Luck";
            _dict[(int) LocalizationProperties.Join] = "Join";
            _dict[(int) LocalizationProperties.UOAM] = "[UOAM]: ";
            _dict[(int) LocalizationProperties.Kick] = "Kick";
            _dict[(int) LocalizationProperties.Help] = "Help";
            _dict[(int) LocalizationProperties.Tell] = "Tell";
            _dict[(int) LocalizationProperties.Real] = "Real";
            _dict[(int) LocalizationProperties.Sync] = "Sync";
            _dict[(int) LocalizationProperties.Self] = "[* SELF *]";
            _dict[(int) LocalizationProperties.Prev] = "<<";
            _dict[(int) LocalizationProperties.Yell] = "[Yell]: ";
            _dict[(int) LocalizationProperties.FasterCasting] = "Faster Casting";
            _dict[(int) LocalizationProperties.ShowPartyMembers] = "Show party members";
            _dict[(int) LocalizationProperties.LightLevel] = "Light level";
            _dict[(int) LocalizationProperties.StoreDesignInProgress] = "Store design in progress in a back up buffer, but do not finalize design.";
            _dict[(int) LocalizationProperties.DisableTab] = "Disable TAB (toggle warmode)";
            _dict[(int) LocalizationProperties.DefenseChanceIncrease] = "Defense Chance Increase";
            _dict[(int) LocalizationProperties.AnisotropicClamp] = "Anisotropic Clamp";
            _dict[(int) LocalizationProperties.FlipMap] = "Flip map";

            Log.Trace("done!");
        }
    }
}
